<?php
/**
 * You are allowed to use this API in your web application.
 *
 * Copyright (C) 2018 by customweb GmbH
 *
 * This program is licenced under the customweb software licence. With the
 * purchase or the installation of the software in your application you
 * accept the licence agreement. The allowed usage is outlined in the
 * customweb software licence which can be found under
 * http://www.sellxed.com/en/software-license-agreement
 *
 * Any modification or distribution is strictly forbidden. The license
 * grants you the installation in one application. For multiuse you will need
 * to purchase further licences at http://www.sellxed.com/shop.
 *
 * See the customweb software licence agreement for more details.
 *
 *
 * @category	Customweb
 * @package		Customweb_UnzerCw
 * @version		1.0.59
 */

/**
 * Metadata version
 */
$sMetadataVersion = '1.1';

/**
 * Module information
 */
$aModule = array(
	'id'           => 'unzercw',
	'title'        => 'UnzerCw',
	'description'  => array(
		'de' => 'Integriert UnzerCw in OXID eSales Shop.',
		'en' => 'Integrates UnzerCw into the OXID eSales shop.'
	),
	'version'      => '1.0.59',
	'author'       => 'customweb GmbH',
	'extend'       => array(
		'module_config' => 'customweb/unzercw/controllers/core/unzercw_module_config',
		'thankyou' => 'customweb/unzercw/controllers/core/unzercw_thankyou',
		'navigation' => 'customweb/unzercw/controllers/core/unzercw_navigation',
		'payment_list' => 'customweb/unzercw/controllers/core/unzercw_payment_list',
		'payment' => 'customweb/unzercw/controllers/core/unzercw_payment',
		'order_list' => 'customweb/unzercw/controllers/core/unzercw_order_list',
		'order' => 'customweb/unzercw/controllers/core/unzercw_order',
		'oxbasketitem' => 'customweb/unzercw/models/core/unzercw_oxbasketitem',
		'oxpayment' => 'customweb/unzercw/models/core/unzercw_oxpayment',
		'oxorder' => 'customweb/unzercw/models/core/unzercw_oxorder',
		'oxuserpayment' => 'customweb/unzercw/models/core/unzercw_oxuserpayment',
		'oxconfig' => 'customweb/unzercw/core/unzercw_oxconfig',
		'oxemail' => 'customweb/unzercw/core/unzercw_oxemail',
		'oxlang' => 'customweb/unzercw/core/unzercw_oxlang',
		'oxinputvalidator' => 'customweb/unzercw/core/unzercw_oxinputvalidator',
		'oxsession' => 'customweb/unzercw/core/unzercw_oxsession',
		'oxwlanguagelist' => 'customweb/unzercw/components/core/widgets/unzercw_oxwlanguagelist',
		'oxwservicemenu' => 'customweb/unzercw/components/core/widgets/unzercw_oxwservicemenu',
		'oxwcurrencylist' => 'customweb/unzercw/components/core/widgets/unzercw_oxwcurrencylist',
	),
	'files'			=> array(
		'unzercw_breakout' => 'customweb/unzercw/controllers/unzercw_breakout.php',
		'unzercw_widget' => 'customweb/unzercw/controllers/unzercw_widget.php',
		'unzercw_redirect' => 'customweb/unzercw/controllers/unzercw_redirect.php',
		'unzercw_cron' => 'customweb/unzercw/controllers/unzercw_cron.php',
		'unzercw_payment' => 'customweb/unzercw/controllers/unzercw_payment.php',
		'unzercw_transaction_refund_form' => 'customweb/unzercw/controllers/admin/unzercw_transaction_refund_form.php',
		'unzercw_payment_settings' => 'customweb/unzercw/controllers/admin/unzercw_payment_settings.php',
		'unzercw_transaction_capture_form' => 'customweb/unzercw/controllers/admin/unzercw_transaction_capture_form.php',
		'unzercw_backendform' => 'customweb/unzercw/controllers/admin/unzercw_backendform.php',
		'unzercw_order_transactions' => 'customweb/unzercw/controllers/admin/unzercw_order_transactions.php',
		'unzercw_transaction_refund' => 'customweb/unzercw/controllers/admin/unzercw_transaction_refund.php',
		'unzercw_transaction_view' => 'customweb/unzercw/controllers/admin/unzercw_transaction_view.php',
		'unzercw_transaction_admin' => 'customweb/unzercw/controllers/admin/unzercw_transaction_admin.php',
		'unzercw_transaction_list' => 'customweb/unzercw/controllers/admin/unzercw_transaction_list.php',
		'unzercw_transaction_capture' => 'customweb/unzercw/controllers/admin/unzercw_transaction_capture.php',
		'unzercw_alias' => 'customweb/unzercw/controllers/unzercw_alias.php',
		'unzercw_process' => 'customweb/unzercw/controllers/unzercw_process.php',
		'unzercw_iframe' => 'customweb/unzercw/controllers/unzercw_iframe.php',
		'unzercw_template' => 'customweb/unzercw/controllers/unzercw_template.php',
		'unzercw_layout' => 'customweb/unzercw/controllers/unzercw_layout.php',
		'unzercw_pending' => 'customweb/unzercw/controllers/unzercw_pending.php',
		'unzercw_endpoint' => 'customweb/unzercw/controllers/unzercw_endpoint.php',

		'UnzerCwConfigurationAdapter' => 'customweb/unzercw/classes/UnzerCwConfigurationAdapter.php',
		'UnzerCwAdapterServerAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterServerAdapter.php',
		'UnzerCwTransactionCleanUpCron' => 'customweb/unzercw/classes/UnzerCwTransactionCleanUpCron.php',
		'UnzerCwLicenseAdapter' => 'customweb/unzercw/classes/UnzerCwLicenseAdapter.php',
		'UnzerCwBackendCancelAdapter' => 'customweb/unzercw/classes/UnzerCwBackendCancelAdapter.php',
		'UnzerCwAdapterHiddenAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterHiddenAdapter.php',
		'UnzerCwTransactionContext' => 'customweb/unzercw/classes/UnzerCwTransactionContext.php',
		'UnzerCwBackendRefundAdapter' => 'customweb/unzercw/classes/UnzerCwBackendRefundAdapter.php',
		'UnzerCwBackendCaptureAdapter' => 'customweb/unzercw/classes/UnzerCwBackendCaptureAdapter.php',
		'UnzerCwOrderContext' => 'customweb/unzercw/classes/UnzerCwOrderContext.php',
		'UnzerCwControlCssClassResolver' => 'customweb/unzercw/classes/UnzerCwControlCssClassResolver.php',
		'UnzerCwAdapterPaymentPageAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterPaymentPageAdapter.php',
		'UnzerCwPaymentMethodSetting' => 'customweb/unzercw/classes/UnzerCwPaymentMethodSetting.php',
		'UnzerCwStorage' => 'customweb/unzercw/classes/UnzerCwStorage.php',
		'UnzerCwPaymentMethod' => 'customweb/unzercw/classes/UnzerCwPaymentMethod.php',
		'UnzerCwLayoutRenderer' => 'customweb/unzercw/classes/UnzerCwLayoutRenderer.php',
		'UnzerCwAdapterIAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterIAdapter.php',
		'UnzerCwSetup' => 'customweb/unzercw/classes/UnzerCwSetup.php',
		'UnzerCwAdapterAbstractAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterAbstractAdapter.php',
		'UnzerCwEndpointAdapter' => 'customweb/unzercw/classes/UnzerCwEndpointAdapter.php',
		'UnzerCwAdapterIframeAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterIframeAdapter.php',
		'UnzerCwHelper' => 'customweb/unzercw/classes/UnzerCwHelper.php',
		'UnzerCwFormControlAgb' => 'customweb/unzercw/classes/UnzerCwFormControlAgb.php',
		'UnzerCwBackendFormRenderer' => 'customweb/unzercw/classes/UnzerCwBackendFormRenderer.php',
		'UnzerCwFormValidatorAgb' => 'customweb/unzercw/classes/UnzerCwFormValidatorAgb.php',
		'UnzerCwTranslationResolver' => 'customweb/unzercw/classes/UnzerCwTranslationResolver.php',
		'UnzerCwPaymentCustomerContext' => 'customweb/unzercw/classes/UnzerCwPaymentCustomerContext.php',
		'UnzerCwTransaction' => 'customweb/unzercw/classes/UnzerCwTransaction.php',
		'UnzerCwFormRenderer' => 'customweb/unzercw/classes/UnzerCwFormRenderer.php',
		'UnzerCwPreparation' => 'customweb/unzercw/classes/UnzerCwPreparation.php',
		'UnzerCwDocument' => 'customweb/unzercw/classes/UnzerCwDocument.php',
		'UnzerCwAdapterAjaxAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterAjaxAdapter.php',
		'UnzerCwLoggingListener' => 'customweb/unzercw/classes/UnzerCwLoggingListener.php',
		'UnzerCwDatabaseConnectionWrapper' => 'customweb/unzercw/classes/UnzerCwDatabaseConnectionWrapper.php',
		'UnzerCwContextRequest' => 'customweb/unzercw/classes/UnzerCwContextRequest.php',
		'UnzerCwAdapterWidgetAdapter' => 'customweb/unzercw/classes/UnzerCwAdapterWidgetAdapter.php',
		'UnzerCwDatabaseDriver' => 'customweb/unzercw/classes/UnzerCwDatabaseDriver.php',

		'unzercw_transaction' => 'customweb/unzercw/models/unzercw_transaction.php',
	),
	'blocks'		=> array(
		array('template' => 'page/checkout/user.tpl', 'block' => 'checkout_user_main', 'file' => 'views/blocks/page/checkout/user/checkout_user_main.tpl'),
		array('template' => 'page/checkout/thankyou.tpl', 'block' => 'checkout_thankyou_info', 'file' => 'views/blocks/page/checkout/thankyou/checkout_thankyou_info.tpl'),
		array('template' => 'page/checkout/order.tpl', 'block' => 'checkout_order_btn_confirm_bottom', 'file' => 'views/blocks/page/checkout/order/checkout_order_btn_confirm_bottom.tpl'),
		array('template' => 'page/checkout/basket.tpl', 'block' => 'checkout_basket_main', 'file' => 'views/blocks/page/checkout/basket/checkout_basket_main.tpl'),
		array('template' => 'page/checkout/payment.tpl', 'block' => 'checkout_payment_errors', 'file' => 'views/blocks/page/checkout/payment/checkout_payment_errors.tpl'),
		array('template' => 'page/checkout/payment.tpl', 'block' => 'select_payment', 'file' => 'views/blocks/page/checkout/payment/select_payment.tpl'),
		array('template' => 'page/checkout/payment.tpl', 'block' => 'checkout_payment_main', 'file' => 'views/blocks/page/checkout/payment/checkout_payment_main.tpl'),
		array('template' => 'page/checkout/payment.tpl', 'block' => 'mb_select_payment', 'file' => 'views/blocks/page/checkout/payment/mb_select_payment.tpl'),
		array('template' => 'page/checkout/payment.tpl', 'block' => 'checkout_payment_nextstep', 'file' => 'views/blocks/page/checkout/payment/checkout_payment_nextstep.tpl'),
		array('template' => 'email/plain/order_cust.tpl', 'block' => 'email_plain_order_cust_paymentinfo', 'file' => 'views/blocks/email/plain/order_cust/email_plain_order_cust_paymentinfo.tpl'),
		array('template' => 'email/html/order_cust.tpl', 'block' => 'email_html_order_cust_paymentinfo_top', 'file' => 'views/blocks/email/html/order_cust/email_html_order_cust_paymentinfo_top.tpl'),
		array('template' => 'module_config.tpl', 'block' => 'admin_module_config_var_types', 'file' => 'views/blocks/module_config/admin_module_config_var_types.tpl'),
	),
	'events'		=> array(
		'onActivate'   => 'UnzerCwSetup::onActivate',
		'onDeactivate' => 'UnzerCwSetup::onDeactivate'
	),
	'templates'		=> array(
		'unzercw_transaction.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction.tpl',
		'unzercw_order_transactions_missing.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_order_transactions_missing.tpl',
		'unzercw_transaction_refund.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction_refund.tpl',
		'unzercw_transaction_list.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction_list.tpl',
		'unzercw_payment_settings.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_payment_settings.tpl',
		'unzercw_order_transactions.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_order_transactions.tpl',
		'unzercw_order_transactions_pending.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_order_transactions_pending.tpl',
		'unzercw_backendform.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_backendform.tpl',
		'unzercw_transaction_refund_form.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction_refund_form.tpl',
		'unzercw_payment_list.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_payment_list.tpl',
		'unzercw_order_transactions_invalid.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_order_transactions_invalid.tpl',
		'unzercw_order_list.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_order_list.tpl',
		'unzercw_payment_settings_invalid.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_payment_settings_invalid.tpl',
		'unzercw_transaction_capture.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction_capture.tpl',
		'unzercw_transaction_capture_form.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction_capture_form.tpl',
		'unzercw_transaction_view.tpl' => 'customweb/unzercw/views/admin/tpl/unzercw_transaction_view.tpl',
		'unzercw_iframe.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/iframe.tpl',
		'unzercw_payment.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/payment.tpl',
		'unzercw_template.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/template.tpl',
		'unzercw_agb.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/agb.tpl',
		'unzercw_layout.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/layout.tpl',
		'unzercw_redirect.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/redirect.tpl',
		'unzercw_widget.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/widget.tpl',
		'unzercw_breakout.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/breakout.tpl',
		'unzercw_pending.tpl' => 'customweb/unzercw/views/azure/tpl/page/unzercw/pending.tpl',
		'unzercw_header_servicemenu.tpl' => 'customweb/unzercw/views/azure/tpl/widgets/unzercw/header/servicemenu.tpl',
		'unzercw_header_currencies.tpl' => 'customweb/unzercw/views/azure/tpl/widgets/unzercw/header/currencies.tpl',
		'unzercw_header_languages.tpl' => 'customweb/unzercw/views/azure/tpl/widgets/unzercw/header/languages.tpl',
	),
	'settings'		=> array(
		array(
			'name' => 'unzercw_operating_mode',
 			'type' => 'cwselect',
 			'value' => 'test',
 			'constraints' => 'test|live',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_public_key_live',
 			'type' => 'str',
 			'value' => '',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_private_key_live',
 			'type' => 'str',
 			'value' => '',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_public_key_test',
 			'type' => 'str',
 			'value' => '',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_private_key_test',
 			'type' => 'str',
 			'value' => '',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_order_id_schema',
 			'type' => 'str',
 			'value' => '{id}',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_payment_reference_schema',
 			'type' => 'str',
 			'value' => '{id}',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_invoice_id_schema',
 			'type' => 'str',
 			'value' => '{id}',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_order_creation',
 			'type' => 'cwselect',
 			'value' => 'after',
 			'constraints' => 'before|after',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_order_id',
 			'type' => 'cwselect',
 			'value' => 'default',
 			'constraints' => 'default|duplicate|enforce',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_delete_failed_orders',
 			'type' => 'cwselect',
 			'value' => 'no',
 			'constraints' => 'yes|no',
 			'group' => 'unzercw',
 		),
		array(
			'name' => 'unzercw_logging_level',
 			'type' => 'cwselect',
 			'value' => 'error',
 			'constraints' => 'error|info|debug',
 			'group' => 'unzercw',
 		),
		//List payment method settings, to avoid deletion upon reactivation
		array(
			'name' => 'creditcard_placeholder_size',
 			'type' => 'select',
 			'value' => 'narrow',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_capturing',
 			'type' => 'select',
 			'value' => 'direct',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'creditcard_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_placeholder_size',
 			'type' => 'select',
 			'value' => 'narrow',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_merchant_name',
 			'type' => 'str',
 			'value' => '',
 			'group' => null,
 		),
		array(
			'name' => 'directdebitssepa_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_merchant_name',
 			'type' => 'str',
 			'value' => '',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_placeholder_size',
 			'type' => 'select',
 			'value' => 'narrow',
 			'group' => null,
 		),
		array(
			'name' => 'securesepa_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'openinvoice_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'secureinvoice_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'secureinvoice_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'secureinvoice_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'secureinvoice_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'secureinvoice_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_capturing',
 			'type' => 'select',
 			'value' => 'direct',
 			'group' => null,
 		),
		array(
			'name' => 'paypal_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'sofortueberweisung_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'giropay_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'przelewy24_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_placeholder_size',
 			'type' => 'select',
 			'value' => 'narrow',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'ideal_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'prepayment_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'eps_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'eps_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'eps_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'eps_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'eps_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'eps_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'eps_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'unzerbanktransfer_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'unzerinstallment_effective_interest_rate',
 			'type' => 'str',
 			'value' => '5.99',
 			'group' => null,
 		),
		array(
			'name' => 'unzerinstallment_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'unzerinstallment_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'unzerinstallment_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'unzerinstallment_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'unzerinstallment_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'alipay_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'wechatpay_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_status_authorized',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_NEW',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_status_uncertain',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_PROBLEMS',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_status_cancelled',
 			'type' => 'select',
 			'value' => 'ORDERFOLDER_FINISHED',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_status_captured',
 			'type' => 'select',
 			'value' => 'no_status_change',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_placeholder_size',
 			'type' => 'select',
 			'value' => 'narrow',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_send_basket',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_send_customer',
 			'type' => 'select',
 			'value' => 'no',
 			'group' => null,
 		),
		array(
			'name' => 'bcmc_authorizationMethod',
 			'type' => 'select',
 			'value' => 'AjaxAuthorization',
 			'group' => null,
 		),


	)
);

require_once 'classes/UnzerCwPreparation.php';
UnzerCwPreparation::alterVarLengths();